name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v5

      - name: Cài đặt Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Cài đặt Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build APK
        run: |
          buildozer -v android debug
          pip install buildozer cython==0.29.36
      - name: Cài đặt thư viện hệ thống
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            libltdl-dev \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Lưu APK
        uses: actions/upload-artifact@v4
        with:
          name: so-xo-apk
          path: bin/*.apk
